apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi
data:
  DOCKER_HOST_ADDRESS: "45.151.166.29"
  ENABLE_P2P: "false"
  JICOFO_AUTH_USER: focus
  JVB_AUTH_USER: jvb
  JVB_BREWERY_MUC: jvbbrewery
  JVB_PORT: "10000"
  JVB_STUN_SERVERS: stun.freifunk-duesseldorf.de:3478
  JVB_TCP_HARVESTER_DISABLED: "true"
  PUBLIC_HOST: jitsi.dev.dorf.world
  PUBLIC_URL: https://jitsi.dev.dorf.world
  TZ: Europe/Berlin
  XMPP_BOSH_URL_BASE: http://127.0.0.1:5280
  XMPP_MUC_DOMAIN: muc.meet.jitsi
  XMPP_SERVER: localhost
  XMPP_DOMAIN: meet.jitsi
  XMPP_AUTH_DOMAIN: auth.meet.jitsi
  XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.jitsi
  