apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi
  labels:
    app.kubernetes.io/name: jitsi
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jitsi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jitsi
    spec:
      containers:
      - name: jicofo
        image: jitsi/jicofo
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: jitsi
        env:
        - name: JICOFO_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jitsi
              key: JICOFO_AUTH_PASSWORD
        - name: JICOFO_COMPONENT_SECRET
          valueFrom:
            secretKeyRef:
              name: jitsi
              key: JICOFO_COMPONENT_SECRET
      - name: jvb
        image: jitsi/jvb
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: jitsi
        env:
        - name: JICOFO_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jitsi
              key: JICOFO_AUTH_PASSWORD
        - name: JVB_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jitsi
              key: JVB_AUTH_PASSWORD
      - name: prosody
        image: jitsi/prosody
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: jitsi
        env:
        - name: JICOFO_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jitsi
              key: JICOFO_AUTH_PASSWORD
        - name: JICOFO_COMPONENT_SECRET
          valueFrom:
            secretKeyRef:
              name: jitsi
              key: JICOFO_COMPONENT_SECRET
        - name: JVB_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jitsi
              key: JVB_AUTH_PASSWORD
      - name: web
        image: jitsi/web
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: jitsi
