apiVersion: v1
kind: Service
metadata:
  name: jvb
  namespace: app-workadventure-jitsi
  labels:
    service: jvb
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app.kubernetes.io/name: jitsi
  type: LoadBalancer
  loadBalancerIP: $(PUBLIC_ADDRESS)
  ports:
  - protocol: UDP
    port: $(JVB_PORT)
    targetPort: $(JVB_PORT)
